services:
  postgres:
    image: postgres:16-alpine
    container_name: rased-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rased_db
      POSTGRES_USER: rased
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rased -d rased_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
